### ISSUE TITLE
Error while preprocessing .graphql file

### ISSUE THREAD

**Issue by isaacunderwood** [dimaMachina/graphql-eslint#2716]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox

     > For example, you can start off by editng the
     > ['basic' example on Stackblitz](https://stackblitz.com/github/B2o5T/graphql-eslint/tree/master/examples/basic).

     > Please make sure the graphql-eslint version under `package.json` matches yours.

- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

After configuring the plugin to run on files with `.graphql` extension, I am getting TypeErrors in my ESLint output:

```
TypeError: [graphql-eslint] Error while preprocessing "src/project/graphql/queries/example.graphql" file

Provided file type must be one of .js, .mjs, .cjs, .jsx, .ts, .mts, .cts, .tsx, .flow, .flow.js, .flow.jsx, .vue, .svelte, .astro, .gts, .gjs 
    at extractExtension (/Users/isaacunderwood/project/node_modules/@graphql-eslint/eslint-plugin/node_modules/@graphql-tools/graphql-tag-pluck/cjs/index.js:162:19)
    at gqlPluckFromCodeStringSync (/Users/isaacunderwood/project/node_modules/@graphql-eslint/eslint-plugin/node_modules/@graphql-tools/graphql-tag-pluck/cjs/index.js:118:21)
    at Object.preprocess (/Users/isaacunderwood/project/node_modules/@graphql-eslint/eslint-plugin/cjs/processor.js:41:66)
    at ProcessorService.preprocessSync (/Users/isaacunderwood/project/node_modules/eslint/lib/services/processor-service.js:48:32)
    at Linter._verifyWithFlatConfigArrayAndProcessor (/Users/isaacunderwood/project/node_modules/eslint/lib/linter/linter.js:1572:51)
    at Linter._verifyWithFlatConfigArray (/Users/isaacunderwood/project/node_modules/eslint/lib/linter/linter.js:2068:25)
    at Linter.verify (/Users/isaacunderwood/project/node_modules/eslint/lib/linter/linter.js:1528:61)
    at Linter.verifyAndFix (/Users/isaacunderwood/project/node_modules/eslint/lib/linter/linter.js:2319:29)
    at verifyText (/Users/isaacunderwood/project/node_modules/eslint/lib/eslint/eslint.js:329:48)
    at ESLint.lintText (/Users/isaacunderwood/project/node_modules/eslint/lib/eslint/eslint.js:930:26)
```

The linting itself still seems to work.

This is our ESLint config:

```
const graphQL = require("@graphql-eslint/eslint-plugin").default;

module.exports = [
    // omitted non-relevant config
    {
        files: ["src/**/*.graphql"],
        plugins: {
            "@graphql-eslint": graphQL,
        },
        processor: graphQL.processor,
        languageOptions: {
            parser: graphQL.parser,
            parserOptions: {
                graphQLConfig: {
                    schema: [
                        "https://omitted.io/graphql/",
                        "libs/shared/graphqlMock/schema.graphql",
                    ],
                    documents: "src/**/*.graphql",
                },
            },
        },
        rules: { ...graphQL.configs["flat/operations-recommended"].rules },
    },
];
```

**To Reproduce** Steps to reproduce the behavior:

Use similar config as above.

**Expected behavior**

**Environment:**

- OS: MacOS (Silicon)
- `@graphql-eslint/eslint-plugin`: 4.0.0-alpha.12
- Node.js: 20.10.0

**Additional context**

**Comment by dimaMachina** [comment]
Please follow the examples, there is no mention of enabling graphql eslint processor on *.graphql files

**Comment by isaacunderwood** [comment]
@dimaMachina ah my bad... all fixed.

Thanks for the quick response 👍
