### ISSUE TITLE
4.0.0-alpha.13: node.typeInfo(...).inputType.getFields is not a function

### ISSUE THREAD

**Issue by bmulholland** [dimaMachina/graphql-eslint#2724]
4.0.0-alpha.12 works fine, but upgrading to .13 throws the error below.

I figure that this is isolated enough (one commit!) that you probably don't need a repro or anything. But let me know if it's not obvious and I can provide more info.

Below is with ESLint 9.14.0. I believe I also repro'd on 9.15.0 but would want to confirm.

```
Rule: "@graphql-eslint/no-deprecated"
    at ObjectValue (file:///Users/bmulholland/dev/recital/recital-frontend/node_modules/.pnpm/@graphql-eslint+eslint-plugin@4.0.0-alpha.13_@types+node@22.9.0_eslint@9.14.0_jiti@2.3.3__gra_j6jwcmpffd355eucckoxqowh74/node_modules/@graphql-eslint/eslint-plugin/esm/rules/no-deprecated/index.js:123:50)
    at ruleErrorHandler (/Users/bmulholland/dev/recital/recital-frontend/node_modules/.pnpm/eslint@9.14.0_jiti@2.3.3/node_modules/eslint/lib/linter/linter.js:1084:48)
    at /Users/bmulholland/dev/recital/recital-frontend/node_modules/.pnpm/eslint@9.14.0_jiti@2.3.3/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/bmulholland/dev/recital/recital-frontend/node_modules/.pnpm/eslint@9.14.0_jiti@2.3.3/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/bmulholland/dev/recital/recital-frontend/node_modules/.pnpm/eslint@9.14.0_jiti@2.3.3/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/Users/bmulholland/dev/recital/recital-frontend/node_modules/.pnpm/eslint@9.14.0_jiti@2.3.3/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/Users/bmulholland/dev/recital/recital-frontend/node_modules/.pnpm/eslint@9.14.0_jiti@2.3.3/node_modules/eslint/lib/linter/node-event-generator.js:337:14)
    at runRules (/Users/bmulholland/dev/recital/recital-frontend/node_modules/.pnpm/eslint@9.14.0_jiti@2.3.3/node_modules/eslint/lib/linter/linter.js:1128:40)
    at #flatVerifyWithoutProcessors (/Users/bmulholland/dev/recital/recital-frontend/node_modules/.pnpm/eslint@9.14.0_jiti@2.3.3/node_modules/eslint/lib/linter/linter.js:1911:31)
```

**Comment by dimaMachina** [comment]
Can you share your code snippet? So i’ll add a test

**Comment by bmulholland** [comment]
It appears to be on a mutation that uses an object as an argument (our server takes args as an input object). Here's an example:

No crash:
```
const nocrash = /* GraphQL */ `
  mutation {
    minimal(t: String) {
      id
    }
  }
`
```

Crash:
```
const crash = /* GraphQL */ `
  mutation {
    minimal(t: { t: String }) {
      id
    }
  }
`
```

**Comment by bmulholland** [comment]
Could have sworn I searched that file for a matching test! I don't know why it didn't catch the issue. I'll update to the latest alpha and try it out.

**Comment by bmulholland** [comment]
Confirmed that the crash is fixed in alpha 15. Nice work!

**Comment by dimaMachina** [comment]
> Confirmed that the crash is fixed in alpha 15. Nice work! Did you figure out why the existing test didn't catch it?

Nope, I just fixed it based on the error you provided, would be nice to have a code fixture which provokes this error

**Comment by bmulholland** [comment]
> would be nice to have a code fixture which provokes this error

Something must be wrong with the test code. I tried the example you linked, and that crashes alpha.13:

```
(main)⚡ [2] % p eslint graphql/test.ts

Oops! Something went wrong! :(

ESLint: 9.14.0

TypeError: Cannot read properties of undefined (reading 'getFields')
Occurred while linting /Users/bmulholland/dev/recital/recital-frontend/graphql/test.ts/0_document.graphql:3
```

test.ts:
```
const test = /* GraphQL */ `
  {
    testObjectField(input: { a: 2 })
  }
`
```
